const banco = [
    {
      id: "0",
      srcImg: "img/Dunk Low 2.png",
      altImg: "Tênis Nike Dunk Low SB WR",
      titleImg:"Tênis Nike Dunk Low SB WR",
      tituloProduto: "Dunk Low Sb Wb",
      precoProduto: 899.99,
      descProduto: "Novo Nike Dunk Low SB red and white, garante à você uma pegada esportiva e streetwear.",
      secao: "Dunk",
    },
    {
      id: "1",
      srcImg: "img/Slide Victory Black.png",
      altImg: "Chinelo Nike Slide Victory Black",
      titleImg:"Chinelo Nike Slide Victory Black",
      tituloProduto: "Slide Victory Black",
      precoProduto: 149.99,
      descProduto: "Novo Chinelo Slide Victory Balck, conforto e estilo em um só produto, garanta já.",
      secao: "Slide",
    },
    {
      id: "2",
      srcImg: "img/Air Jordan 1 Mid Lakers.png",
      altImg: "Tênis Nike Air Jordan 1 Mid Lakers",
      titleImg:"Tênis Nike Air Jordan 1 Mid Lakers",
      tituloProduto: "Jordan 1 Mid Lakers",
      precoProduto: 899.99,
      descProduto: "Novo Air Jordan 1 Mid x Lakers, para os amantes do basquete e streetwear.",
      secao: "Air Jordan",
    },
    {
      id: "3",
      srcImg: "img/Slide Victory Fem..png",
      altImg: "Chinelo Nike Slide Victory Feminino",
      titleImg:"Chinelo Nike Slide Victory Feminino",
      tituloProduto: "Slide Victory Pink",
      precoProduto: 149.99,
      descProduto: "Novo Chinelo Slide Victory Feminino, conforto e estilo em um só produto, garanta já.",
      secao: "Slide",
    },
    {
      id: "4",
      srcImg: "img/Air Jordan 1 Mid.png",
      altImg: "Tênis Nike Air Jordan 1 Mid GW",
      titleImg:"Tênis Nike Air Jordan 1 Mid GW",
      tituloProduto: "Jordan 1 Mid Wc",
      precoProduto: 899.99,
      descProduto: "Novo Air Jordan 1 Mid white and grey, para fechar seu estilo off-white com muito conforto.",
      secao: "Air Jordan",
      
    },
    {
      id: "5",
      srcImg: "img/Dunk Low 1.png",
      altImg: "Tênis Nike Dunk SB Low BW",
      titleImg:"Tênis Nike Dunk SB Low BW",
      tituloProduto: "Dunk Low Sb Wb",
      precoProduto: 899.99,
      descProduto: "Novo Nike Dunk Low SB Black and white, garante à você uma pegada esportiva e streetwear.",
      secao: "Dunk",
    },
  ];